name: PR Review Validation

on:
  pull_request:
    types:
      - opened
      - edited
      - review_requested
      - review_dismissed
      - labeled

jobs:
  review-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check pull request reviews
      id: review_check
      run: |
        PR_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews"
        
        # Get all reviews for the PR
        REVIEWS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $PR_URL)

        # Get the count of approvals
        APPROVALS=$(echo "$REVIEWS" | jq '[.[] | select(.state == "APPROVED")] | length')
        
        # Check if there are at least 2 approvals
        if [ "$APPROVALS" -lt 2 ]; then
          echo "Error: PR needs at least 2 approvals."
          exit 1
        fi

        # Check if any review was rejected
        REJECTED=$(echo "$REVIEWS" | jq '[.[] | select(.state == "CHANGES_REQUESTED")] | length')
        
        if [ "$REJECTED" -gt 0 ]; then
          echo "Error: PR contains a rejected review."
          exit 1
        fi

        echo "PR has at least 2 approvals and no rejected reviews."
