name: Selenium Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Start Local Web Server
      run: |
        python -m http.server 3000 &  # Serves the site at localhost:3000
        sleep 3  # Give the server a few seconds to start

    - name: Run Selenium Test
      run: |
        python using_selenium_tests.py

    - name: Stop Web Server
      if: always()
      run: |
        pkill -f "python -m http.server"
